leancloud:
  appId: ${LC_APP_ID}
  appKey: ${LC_APP_KEY}
  baseUrl: "https://api.leancloud.cn/1.1"

jerseyClient:
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: true
  gzipEnabledForRequests: true
  chunkedEncodingEnabled: true
